try:
    print(x)
finally:
    print("Exception occured but not handlled")  # this will always execute
